[package]
name = "r_engine"
version = "0.1.0"
authors = ["Usummon <breakcreak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.32.2"
gl = "0.14.0"